### ISSUE TITLE
Website displayed on README gives error 404.

### ISSUE THREAD

**Issue by arcogabbo** [moritzruth/spdx-license-data#1]
As title says, the URL on the README which hosts the json files gives error 404.
I can take all the files on the `data` directory of the library but i would prefer to fetch them online in any moment.
The URL you provided is `https://license-data.moritzruth.de/` .

**Comment by moritzruth** [comment]
Thank you for pointing that out.

It should work now: https://license-data.moritzruth.de/licenses.json

**Comment by arcogabbo** [comment]
Thank you for the fast response and fix. Now it works fine.
